apiVersion: operator.rethinkdb.com/v1alpha1
kind: RethinkDB
metadata:
  name: rethinkdb-custom-example
  namespace: default
  labels:
    app: rethinkdb
    cluster: rethinkdb-custom-example
spec:
  nodes: 3
  webAdminEnabled: true
  pod:
    resources:
      limits:
        cpu: 1.0
        memory: 3Gi
      requests:
        cpu: 0.3
        memory: 2Gi
    persistentVolumeClaimSpec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
