apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rethinkdbs.operator.rethinkdb.com
spec:
  group: operator.rethinkdb.com
  names:
    kind: RethinkDB
    listKind: RethinkDBList
    plural: rethinkdbs
    singular: rethinkdb
    shortNames:
      - rdb
  scope: Namespaced
  version: v1alpha1
