#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export RELEASE_VERSION=`cat version/version.go | grep "Version =" | awk '{ print $3 }' | sed s/\"//g`

operator-sdk build jmckind/rethinkdb-operator:${RELEASE_VERSION}
docker push jmckind/rethinkdb-operator:${RELEASE_VERSION}
