#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

export KUBERNETES_SERVICE_HOST=${KUBERNETES_SERVICE_HOST:=192.168.99.100}
export KUBERNETES_SERVICE_PORT=${KUBERNETES_SERVICE_PORT:=8443}

SERVICE_ACCOUNT_DIR=/var/run/secrets/kubernetes.io/serviceaccount
mkdir -p ${SERVICE_ACCOUNT_DIR}
touch ${SERVICE_ACCOUNT_DIR}/token

go test ./... -timeout 120s -v -short -cover -coverprofile=tmp/_output/coverage.out
